version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "student-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1d0cwz0fktx3z"
s3_prefix = "student-api"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
